// Generated by CoffeeScript 1.7.1
(function() {
  var App;

  App = Ember.Application.create({
    LOG_TRANSITIONS: true
  });

  App.Router.map(function() {
    this.route('about');
    this.route('administrations');
    this.route('themes');
    return this.route('focusareas');
  });

  App.IndexRoute = Ember.Route.extend({
    model: function() {
      return ["red", "yellow", "blue"];
    }
  });

}).call(this);

//# sourceMappingURL=app.map
