// Generated by CoffeeScript 1.7.1
(function() {
  App.AdministrationRoute = Ember.Route.extend({
    model: function(params) {
      return this.store.findAll('theme');
    }
  });

}).call(this);

//# sourceMappingURL=administration.map
