// Generated by CoffeeScript 1.7.1
(function() {
  App.ApplicationRoute = Ember.Route.extend({
    actions: {
      loading: function() {
        NProgress.start();
        this.router.one('didTransition', function() {
          return setTimeout((function() {
            return NProgress.done();
          }), 50);
        });
        return true;
      },
      error: function() {
        return setTimeout((function() {
          return NProgress.done();
        }), 50);
      }
    }
  });

}).call(this);

//# sourceMappingURL=application.map
