// Generated by CoffeeScript 1.7.1
(function() {
  App.GraphRoute = Ember.Route.extend({
    model: function() {
      return this.store.findAll('strategy');
    }
  });

}).call(this);

//# sourceMappingURL=graph.map
