// Generated by CoffeeScript 1.7.1
(function() {
  App.StrategiesAdministrationRoute = Ember.Route.extend({
    model: function(params) {
      return Ember.Object.create({
        administration: this.store.find('administration', params.administration_id),
        themes: this.store.findAll('theme')
      });
    },
    setupController: function(controller, model) {
      controller.set('administration', model.administration);
      return controller.set('themes', model.themes);
    }
  });

}).call(this);

//# sourceMappingURL=strategiesAdministration.map
