// Generated by CoffeeScript 1.7.1
(function() {
  App.StrategiesAdministrationRoute = Ember.Route.extend({
    model: function(params) {
      console.log("StrategiesAdministrationRoute params:", params);
      return this.store.find('theme');
    }
  });

}).call(this);

//# sourceMappingURL=strategiesAdministration.map
