// Generated by CoffeeScript 1.7.1
(function() {
  App.StrategiesRoute = Ember.Route.extend({
    model: function(params) {
      return this.store.findAll('administration');
    },
    afterModel: function(administrations, transition) {
      if (administrations.get("firstObject") != null) {
        return this.transitionTo("/strategies/administration/" + administrations.get("firstObject").get('id'));
      }
    }
  });

}).call(this);

//# sourceMappingURL=strategies.map
