// Generated by CoffeeScript 1.7.1
(function() {
  App.StrategiesAdministrationRoute = Ember.Route.extend({
    model: function(params) {
      return this.store.findAll('theme');
    },
    afterModel: function(themes, transition) {}
  });

}).call(this);

//# sourceMappingURL=strategiesAdministration.map
