// Generated by CoffeeScript 1.7.1
(function() {
  App.ThemesRoute = Ember.Route.extend({
    model: function() {
      return this.store.find('theme');
    }
  });

  App.ThemesNewRoute = Ember.Route.extend({
    model: function() {
      return this.store.createRecord('theme');
    }
  });

  App.ThemesEditRoute = Ember.Route.extend({
    model: function(params) {
      return this.modelFor('theme', params);
    }
  });

}).call(this);

//# sourceMappingURL=themes.map
