// Generated by CoffeeScript 1.7.1
(function() {
  App.Administrations.FIXTURES = [
    {
      id: 1,
      name: "OPB",
      color: "#000"
    }, {
      id: 2,
      name: "SSB",
      salary: "#fff"
    }
  ];

  describe('The administration page should', function() {
    beforeEach(function() {
      return visit("/administrations");
    });
    return describe('contain a table', function() {
      it('with a header and two columns', function() {
        return andThen(function() {
          findWithAssert('table.table');
          return expect(find('table.table thead tr th').length).to.equal(3);
        });
      });
      return describe('with a table body', function() {
        it('with rows of administrations', function() {
          return andThen(function() {
            return expect(find('table.table tbody tr').length).to.equal(2);
          });
        });
        return it('the last columns of each row should contain RUD buttons', function() {
          return expect(find('table.table tbody tr td button').length).to.equal(6);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=administrations_spec.map
