// Generated by CoffeeScript 1.7.1
(function() {
  beforeEach(function() {
    Ember.run(function() {
      App.reset();
    });
    Ember.testing = true;
  });

  afterEach(function() {
    Ember.testing = false;
  });

  after(function() {
    Ember.run(function() {
      App.reset();
    });
  });

  describe("Array", function() {
    it("should return -1 when the value is not present", function() {
      return expect(true).to.equal(true);
    });
  });

}).call(this);

//# sourceMappingURL=app_spec.map
