// Generated by CoffeeScript 1.7.1
(function() {
  describe("The home page should display", function() {
    beforeEach(function() {
      return visit("/");
    });
    it('the app title and description elements', function() {
      return andThen(function() {
        findWithAssert('h2');
        return findWithAssert('div.description');
      });
    });
    return describe('a navbar that has a', function() {
      it('a working title link', function() {
        return andThen(function() {
          var $el;
          $el = findWithAssert('.title-link');
          click($el);
          return expect(currentURL()).to.equal('/');
        });
      });
      it('a working administrations link', function() {
        return andThen(function() {
          var $el;
          $el = findWithAssert('.administrations-link');
          click($el);
          return expect(currentURL()).to.equal('/administrations');
        });
      });
      it('a working themes link', function() {
        return andThen(function() {
          var $el;
          $el = findWithAssert('.themes-link');
          click($el);
          return expect(currentURL()).to.equal('/themes');
        });
      });
      it('a working focus areas link', function() {
        return andThen(function() {
          var $el;
          $el = findWithAssert('.focusareas-link');
          click($el);
          return expect(currentURL()).to.equal('/focusareas');
        });
      });
      return it('a working about link', function() {
        return andThen(function() {
          var $el;
          $el = findWithAssert('.about-link');
          click($el);
          return expect(currentURL()).to.equal('/about');
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=app_spec.map
