// Generated by CoffeeScript 1.7.1
(function() {
  describe("The home page should display", function() {
    it('the app title and description elements', function() {
      visit("/");
      return andThen(function() {
        findWithAssert('h2');
        return findWithAssert('div.description');
      });
    });
    return describe('a navbar that has', function() {
      it('a working title link', function() {
        return assertNavbarLink('');
      });
      it('a working administrations link', function() {
        return assertNavbarLink('administrations');
      });
      it('a working themes link', function() {
        return assertNavbarLink('themes');
      });
      it('a working focus areas link', function() {
        return assertNavbarLink('focusareas');
      });
      return it('a working about link', function() {
        return assertNavbarLink('about');
      });
    });
  });

}).call(this);

//# sourceMappingURL=app_spec.map
