// Generated by CoffeeScript 1.7.1
(function() {
  describe('Focusareas should', function() {
    describe('should have a model that', function() {
      it('should have a content property', function() {
        var contentProperty;
        contentProperty = App.Focusarea.metaForProperty('definition');
        return expect(contentProperty.type).to.equal('string');
      });
      it('should have a focusareas property', function() {
        var contentProperty;
        contentProperty = App.Focusarea.metaForProperty('theme');
        return expect(contentProperty.type).to.equal('theme');
      });
      return it('can be created', function() {
        visit("/themes");
        return andThen(function() {
          return Ember.run(function() {
            var focusarea, store, theme;
            store = App.__container__.lookup('store:main');
            theme = store.createRecord("theme", {
              id: 4,
              definition: 'theme definition'
            });
            focusarea = store.createRecord("focusarea", {
              id: 5,
              definition: 'focusarea definition'
            });
            focusarea.save();
            theme.get("focusareas").then(function(focusareas) {
              focusareas.pushObject(focusarea);
              return theme.save();
            });
            expect(focusarea.get('definition')).to.equal('focusarea definition');
            return store.find('theme', 4).then(function(theme) {
              return theme.get('focusareas').then(function() {
                return expect(theme.get('focusareas').get('length')).to.equal(1);
              });
            });
          });
        });
      });
    });
    return describe('a focusareas page', function() {
      it('should have an add new focusarea button', function() {
        visit('/themes/4/focusareas');
        return andThen(function() {
          return findWithAssert('a.add-focusarea');
        });
      });
      it('should direct to the new route when clicked', function() {
        visit('/themes/4/focusareas');
        return andThen(function() {
          click('a.add-focusarea');
          return expect(currentURL()).to.equal('/themes/4/focusareas/new');
        });
      });
      return it('should have table with a header and two columns', function() {
        visit('/themes/4/focusareas');
        return andThen(function() {
          return expect(find('ul.focusarea-definitions li').length).to.equal(1);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=focusareas_spec.map
