// Generated by CoffeeScript 1.7.1
(function() {
  describe('Graph should', function() {
    return it('TRUE', function() {
      return true;
    });
  });

}).call(this);

//# sourceMappingURL=graph_spec.map
