// Generated by CoffeeScript 1.7.1
(function() {
  describe('Strategies should', function() {
    describe('have a model that', function() {
      it('should have a description property', function() {
        var descriptionProperty;
        descriptionProperty = App.Strategy.metaForProperty('description');
        return expect(descriptionProperty.type).to.equal('string');
      });
      it('should have a administration property', function() {
        var administrationProperty;
        administrationProperty = App.Strategy.metaForProperty('administration');
        return expect(administrationProperty.type).to.equal('administration');
      });
      it('should have a focusarea property', function() {
        var focusareaProperty;
        focusareaProperty = App.Strategy.metaForProperty('focusarea');
        return expect(focusareaProperty.type).to.equal('focusarea');
      });
      return it('can be created', function() {
        return Ember.run(function() {
          var administration, store;
          store = App.__container__.lookup('store:main');
          administration = store.createRecord("administration", {
            name: 'administration created in strategies spec',
            color: '#000'
          });
          administration.save().then(function() {
            var theme;
            theme = store.createRecord("theme", {
              definition: 'theme created in strategies spec'
            });
            return theme.save().then(function() {
              var focusarea;
              focusarea = store.createRecord("focusarea", {
                definition: 'focusarea created in strategies spec',
                theme: theme
              });
              return focusarea.save().then(function() {
                var strategy;
                theme.get("focusareas").pushObject(focusarea);
                theme.save();
                strategy = store.createRecord('strategy', {
                  description: 'Strategy description',
                  administration: administration,
                  focusarea: focusarea
                });
                return strategy.save().then(function() {
                  administration.get('strategies').pushObject(strategy);
                  administration.save();
                  focusarea.get('strategies').pushObject(strategy);
                  return focusarea.save();
                });
              });
            });
          });
          return wait(500);
        });
      });
    });
    return describe('a strategy page that', function() {
      it('should have a list of administration tabs', function() {
        visit("/strategies");
        return andThen(function() {
          return expect(find('ul.strategies-administrations-tabs li').length).to.equal(3);
        });
      });
      it('should have a list of administration tabs that each can be selected', function() {
        visit("/strategies");
        return andThen(function() {
          return click('ul.strategies-administrations-tabs li a').then(function() {
            return expect(find('ul.strategies-administrations-tabs li').length).to.equal(3);
          });
        });
      });
      it('should direct to the new route when clicked', function() {
        visit("/strategies");
        return andThen(function() {
          return click('ul.strategies-administrations-tabs li:contains("administration created in strategies spec") a').then(function() {
            return expect(currentURL()).to.match(/^\/strategies\/administration\/.*$/);
          });
        });
      });
      it('should have a list of themes', function() {
        visit('/strategies');
        return andThen(function() {
          return click('ul.strategies-administrations-tabs li:contains("administration created in strategies spec") a').then(function() {
            return expect(find('div.strategies-administrations-tab.active div.strategies-theme').length).to.equal(4);
          });
        });
      });
      it('should have a list of focusareas', function() {
        visit('/strategies');
        return andThen(function() {
          return click('ul.strategies-administrations-tabs li:contains("administration created in strategies spec") a').then(function() {
            return expect(find('div.strategies-focusarea').length).to.equal(2);
          });
        });
      });
      return it('should have a list of focusareas that can be checked', function() {
        visit('/strategies');
        return andThen(function() {
          return click('ul.strategies-administrations-tabs li:contains("administration created in strategies spec") a').then(function() {
            return click('div.strategies-administrations-tab.active label.strategy-focusarea:contains("focusarea created in strategies spec") input').then(function() {
              return visit('/strategies').andThen(function() {
                return click('ul.strategies-administrations-tabs li:contains("administration created in strategies spec") a').then(function() {
                  return expect(find('div.strategies-administrations-tab.active label.strategy-focusarea:contains("focusarea created in strategies spec") input').is(':checked')).equal(true);
                });
              });
            });
          });
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=strategies_spec.map
