// Generated by CoffeeScript 1.7.1
(function() {
  before(function() {
    Ember.Test.adapter = Ember.Test.MochaAdapter.create(null);
    App.setupForTesting();
    return App.injectTestHelpers();
  });

  beforeEach(function() {
    Ember.run(function() {
      App.reset();
    });
    Ember.testing = true;
  });

  afterEach(function() {
    Ember.testing = false;
  });

}).call(this);

//# sourceMappingURL=test_helper.map
