// Generated by CoffeeScript 1.7.1
(function() {
  before(function() {
    $.ajax({
      async: false,
      url: "http://localhost:4567/reset_db/sip_ember_test_db",
      success: function(data) {
        return console.log("LOADED THE TEST DB", data);
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log("ERROR LOADING THE TEST DB", jqXHR, textStatus, errorThrown);
        return request.abort();
      }
    });
    App.ApplicationAdapter = DS.RESTAdapter.extend({
      namespace: 'api',
      host: 'http://127.0.0.1:4567',
      corsWithCredentials: true
    });
    Ember.Test.adapter = Ember.Test.MochaAdapter.create();
    App.setupForTesting();
    App.injectTestHelpers();
    return Ember.Notify.reopen({
      timeout: 1
    });
  });

  beforeEach(function() {
    Ember.run(function() {
      App.reset();
    });
    Ember.testing = true;
  });

  afterEach(function() {
    Ember.testing = false;
  });

  after(function() {
    return $.ajax({
      async: false,
      url: "http://localhost:4567/select_db/sip_ember_db",
      success: function(data) {
        return console.log("LOADED THE PROD DB" + data);
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log("ERROR LOADING THE PROD DB", jqXHR, textStatus, errorThrown);
        return request.abort();
      }
    });
  });

  Ember.Test.registerAsyncHelper("assertNavbarLink", function(app, value) {
    visit("/");
    andThen(function() {
      var $el;
      if (value !== '') {
        $el = findWithAssert('.' + value + '-link');
      } else {
        $el = findWithAssert('.title-link');
      }
      click($el);
      return expect(currentURL()).to.equal('/' + value);
    });
  });

}).call(this);

//# sourceMappingURL=test_helper.map
