// Generated by CoffeeScript 1.7.1
(function() {
  describe('Themes should', function() {
    describe('should have a model that', function() {
      it('should have a content property', function() {
        var contentProperty;
        contentProperty = App.Theme.metaForProperty('definition');
        return expect(contentProperty.type).to.equal('string');
      });
      it('should have a focusareas property', function() {
        var contentProperty;
        contentProperty = App.Theme.metaForProperty('focusareas');
        return expect(contentProperty.type).to.equal('focusarea');
      });
      return it('can be created', function() {
        visit("/themes");
        return andThen(function() {
          return Ember.run(function() {
            var store, theme;
            store = App.__container__.lookup('store:main');
            theme = store.createRecord("theme", {
              id: 3,
              definition: 'theme definition'
            });
            theme.save();
            return expect(theme.get('definition')).to.equal('theme definition');
          });
        });
      });
    });
    describe('a themes page', function() {
      it('should have an add new theme button', function() {
        visit('/themes');
        return andThen(function() {
          return findWithAssert('a.add-theme');
        });
      });
      it('should direct to the new route when clicked', function() {
        visit('/themes');
        return andThen(function() {
          click('a.add-theme');
          return expect(currentURL()).to.equal('/themes/new');
        });
      });
      return it('should display the first available theme\'s focusareas if any', function() {
        visit('/themes');
        return andThen(function() {
          return expect(currentURL()).to.equal('/themes/1/focusareas');
        });
      });
    });
    describe('a new theme page that', function() {
      beforeEach(function() {
        return visit("/themes");
      });
      it('should have a field and a submit button', function() {
        return andThen(function() {
          return click('a.add-theme').then(function() {
            findWithAssert('form');
            findWithAssert('#definition');
            findWithAssert("button.submit-button");
            return findWithAssert("button.cancel-button");
          });
        });
      });
      it('should be possible to cancel the update', function() {
        visit("/themes");
        return andThen(function() {
          return click('a.add-theme').then(function() {
            return click('button.cancel-button').then(function() {
              return expect(currentURL()).to.equal('/themes/1/focusareas');
            });
          });
        });
      });
      it('should create a new theme entry when submit gets clicked', function() {
        return andThen(function() {
          click('a.add-theme');
          return fillIn('#definition', 'theme-definition1').click('button.submit-button').then(function() {
            return expect(currentURL()).to.equal('/themes/fixture-9/focusareas');
          });
        });
      });
      it('should be valid', function() {
        visit("/themes/new");
        return andThen(function() {
          return fillIn('#definition', '').click('button.submit-button').then(function() {
            return expect(currentURL()).to.equal('/themes/new');
          });
        });
      });
      it('should transition to the the themes page', function() {
        visit("/themes/new");
        return andThen(function() {
          return fillIn('#definition', 'theme-definition2').click('button.submit-button').then(function() {
            return expect(find('ul.theme-definitions li').length).to.equal(5);
          });
        });
      });
      return it('should have themes that each can be clicked to be edited', function() {
        visit("/themes");
        return andThen(function() {
          return findWithAssert('ul.theme-definitions li:contains("theme-definition2") a');
        });
      });
    });
    return describe('an edit theme page that', function() {
      beforeEach(function() {
        return visit("/themes");
      });
      it('should be accessed from the themes page', function() {
        return andThen(function() {
          return click('li:contains("theme-definition1") > a.edit-theme').then(function() {
            findWithAssert('form');
            findWithAssert('#definition');
            findWithAssert("button.update-button");
            return findWithAssert("button.delete-button");
          });
        });
      });
      it('should be possible to update the record', function() {
        return andThen(function() {
          return click('li:contains("theme-definition1") > a.edit-theme').then(function() {
            return fillIn('#definition', 'theme-definition3').click('button.update-button').then(function() {
              expect(currentURL()).to.equal('/themes/fixture-9/focusareas');
              return findWithAssert('li:contains("theme-definition3") > a.active');
            });
          });
        });
      });
      it('should be possible to cancel the update', function() {
        return andThen(function() {
          return click('li:contains("theme-definition3") > a.edit-theme').then(function() {
            return click('button.cancel-button').then(function() {
              return expect(currentURL()).to.equal('/themes/fixture-9/focusareas');
            });
          });
        });
      });
      it('should be possible to delete a theme without focusareas', function() {
        return andThen(function() {
          return click('li:contains("theme-definition3") > a.edit-theme').then(function() {
            return click('button.delete-button').then(function() {
              expect(currentURL()).to.equal('/themes/1/focusareas');
              return expect(find('ul.theme-definitions li').length).to.equal(4);
            });
          });
        });
      });
      return it('should not be possible to delete a theme with focusareas', function() {
        return andThen(function() {
          return click('li:contains("theme1") > a.edit-theme').then(function() {
            return click('button.delete-button').then(function() {
              return expect(currentURL()).to.equal('/themes/2/focusareas');
            });
          });
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=themes_spec.map
