// Generated by CoffeeScript 1.7.1
(function() {
  App.AdministrationsController = Ember.ArrayController.extend({
    administrationsCount: (function() {
      var length;
      length = this.get('model.length');
      if (!length) {
        return 0;
      } else {
        return length;
      }
    }).property('@each')
  });

}).call(this);

//# sourceMappingURL=administrations.map
