// Generated by CoffeeScript 1.7.1
(function() {
  App.AdministrationController = Ember.ArrayController.extend({
    needs: "strategies",
    strategies: Ember.computed.alias("controllers.strategies")
  });

}).call(this);

//# sourceMappingURL=administration.map
