// Generated by CoffeeScript 1.7.1
(function() {
  App.AdministrationStrategyController = Ember.ObjectController.extend({
    needs: 'strategiesAdministration',
    strategiesAdministration: Ember.computed.alias("controllers.strategiesAdministration"),
    init: function() {
      var administration, focusarea, self;
      focusarea = this.get('model');
      administration = this.get('strategiesAdministration.administration');
      self = this;
      return this.store.find("strategy", {
        focusarea: focusarea.get('id'),
        administration: administration.get('id')
      }).then(function(result) {
        var strategy;
        console.log("FOUND:", result.get('length'));
        if (result.get('length') === 0) {
          console.log("CREATING...");
          strategy = self.store.createRecord('strategy', {
            isSelected: false,
            administration: administration,
            focusarea: focusarea
          });
          console.log("SAVING...");
          return strategy.save().then(function() {
            console.log("SAVING AND PUSHING...");
            administration.get('strategies').pushObject(strategy);
            administration.save();
            focusarea.get('strategies').pushObject(strategy);
            focusarea.save();
            console.log("STRATEGY:", strategy);
            return self.set('model', strategy);
          });
        } else {
          return self.set('model', result.get('firstObject'));
        }
      });
    }
  });

}).call(this);

//# sourceMappingURL=administrationStrategy.map
