// Generated by CoffeeScript 1.7.1
(function() {
  App.AdministrationsNewController = Ember.ObjectController.extend({
    actions: {
      submit: function() {
        var administration;
        administration = this.get('model');
        administration.save();
        return this.transitionToRoute('/administrations');
      }
    }
  });

}).call(this);

//# sourceMappingURL=administrationsNew.map
