// Generated by CoffeeScript 1.7.1
(function() {
  App.AdministrationsController = Ember.Controller.extend({
    actions: {
      showModal: function() {
        return console.log("Fireing showModal");
      }
    }
  });

  App.AdministrationsNewController = Ember.Controller.extend({
    actions: {
      showModal: function() {
        console.log("showModal clicked!!");
        return Bootstrap.ModalManager.show('administrationsNewModal');
      },
      submit: function() {
        return console.log("submit");
      },
      cancel: function() {
        console.log("close");
        return transitionTo('administrations');
      }
    },
    modalButtons: [
      Ember.Object.create({
        title: "Submit",
        clicked: "submit"
      }), Ember.Object.create({
        title: "Cancel",
        clicked: "cancel",
        dismiss: "modal"
      })
    ]
  });

}).call(this);

//# sourceMappingURL=administrations.map
