// Generated by CoffeeScript 1.7.1
(function() {
  App.AdministrationsEditController = Ember.ObjectController.extend({
    actions: {
      update: function() {
        var administration;
        administration = this.get('model');
        return this.utility.updateOrSave(this, administration);
      },
      "delete": function() {
        var administration;
        administration = this.get('model');
        administration.destroyRecord();
        return this.transitionToRoute('/administrations');
      },
      cancel: function() {
        return this.transitionToRoute('/administrations');
      }
    }
  });

}).call(this);

//# sourceMappingURL=administrationsEdit.map
