// Generated by CoffeeScript 1.7.1
(function() {
  App.FocusareasNewController = Ember.ObjectController.extend({
    needs: ['focusareas'],
    actions: {
      submit: function() {
        var focusarea, shouldSave;
        focusarea = this.get('model');
        shouldSave = true;
        if (Ember.isEmpty(focusarea.get('definition'))) {
          this.notify.danger("Definition cannot be empty.");
          shouldSave = false;
        }
        if (shouldSave) {
          this.store.find('theme', this.get('theme_id')).then(function(theme) {
            return theme.get("focusareas").then(function(focusareas) {
              focusareas.pushObject(focusarea);
              theme.save();
              return focusarea.save();
            });
          });
          return this.transitionToRoute('/themes/' + this.get('theme_id') + '/focusareas');
        } else {
          return this.transitionToRoute('/themes/' + this.get('theme_id') + '/focusareas/new');
        }
      },
      cancel: function() {
        return this.transitionToRoute('/themes/' + this.get('theme_id') + '/focusareas');
      }
    }
  });

}).call(this);

//# sourceMappingURL=focusareasNew.map
