// Generated by CoffeeScript 1.7.1
(function() {
  App.FocusareasNewController = Ember.ObjectController.extend({
    actions: {
      submit: function() {
        var focusarea, self, shouldSave, theme_id;
        focusarea = this.get('model');
        shouldSave = true;
        theme_id = this.utility.themeId(window.location.href);
        if (Ember.isEmpty(focusarea.get('definition'))) {
          this.notify.danger("Definition cannot be empty.");
          shouldSave = false;
        }
        if (shouldSave) {
          self = this;
          return this.store.find('theme', theme_id).then(function(theme) {
            focusarea.set('theme', theme);
            return focusarea.save().then(function() {
              return self.transitionToRoute('/themes/' + theme_id + '/focusareas');
            });
          });
        } else {
          return this.transitionToRoute('/themes/' + theme_id + '/focusareas/new');
        }
      },
      cancel: function() {
        return this.transitionToRoute('/themes/' + this.utility.themeId(window.location.href) + '/focusareas');
      }
    }
  });

}).call(this);

//# sourceMappingURL=focusareasNew.map
