// Generated by CoffeeScript 1.7.1
(function() {
  App.FocusareasEditController = Ember.ObjectController.extend({
    actions: {
      update: function() {
        var focusarea, shouldSave, themeId;
        focusarea = this.get('model');
        shouldSave = true;
        themeId = this.get('selectedTheme');
        if (Ember.isEmpty(focusarea.get('definition'))) {
          this.notify.danger("Definition cannot be empty.");
          shouldSave = false;
        }
        if (themeId == null) {
          this.notify.danger("You have to create themes before creating focus areas!");
          shouldSave = false;
        }
        if (shouldSave) {
          this.store.find('theme', themeId).then(function(theme) {
            return theme.get("focusareas").then(function(focusareas) {
              focusareas.pushObject(focusarea);
              theme.save();
              return focusarea.save();
            });
          });
          return this.transitionToRoute('/focusareas');
        } else {
          return this.transitionToRoute('/focusareas/edit');
        }
      },
      "delete": function() {
        var administration;
        administration = this.get('model');
        administration.destroyRecord();
        return this.transitionToRoute('/focusareas');
      },
      cancel: function() {
        return this.transitionToRoute('/focusareas');
      }
    }
  });

}).call(this);

//# sourceMappingURL=focusareasEdit.map
