// Generated by CoffeeScript 1.7.1
(function() {
  App.FocusareasEditController = Ember.ObjectController.extend({
    actions: {
      update: function() {
        var focusarea, shouldSave;
        focusarea = this.get('model');
        shouldSave = true;
        if (Ember.isEmpty(focusarea.get('definition'))) {
          this.notify.danger("Definition cannot be empty.");
          shouldSave = false;
        }
        if (shouldSave) {
          focusarea.save();
          return this.transitionToRoute('/focusareas');
        } else {
          return this.transitionToRoute('/focusareas/edit');
        }
      },
      "delete": function() {
        var administration;
        administration = this.get('model');
        administration.destroyRecord();
        return this.transitionToRoute('/focusareas');
      },
      cancel: function() {
        return this.transitionToRoute('/focusareas');
      }
    }
  });

}).call(this);

//# sourceMappingURL=focusareasEdit.map
