// Generated by CoffeeScript 1.7.1
(function() {
  App.FocusareasNewController = Ember.ObjectController.extend({
    actions: {
      submit: function() {
        var focusarea, shouldSave;
        focusarea = this.get('model');
        shouldSave = true;
        if (Ember.isEmpty(focusarea.get('definition'))) {
          this.notify.danger("Definition cannot be empty.");
          shouldSave = false;
        }
        if (shouldSave) {
          focusarea.save();
          return this.transitionToRoute('/focusareas');
        } else {
          return this.transitionToRoute('/focusareas/new');
        }
      },
      cancel: function() {
        return this.transitionToRoute('/focusareas');
      }
    }
  });

}).call(this);

//# sourceMappingURL=focusareasNew.map
