// Generated by CoffeeScript 1.7.1
(function() {
  App.GraphController = Ember.ArrayController.extend({
    nodes: [],
    edges: [],
    data: (function() {
      var dataset;
      console.log("fired!");
      dataset = {
        nodes: JSON.parse(JSON.stringify(this.get('nodes'))),
        edges: this.get('edges')
      };
      return dataset;
    }).property('nodes', 'edges'),
    actions: {
      loadStrategies: function() {
        var self, strategies;
        console.log("NODE:", this.get('nodes'));
        console.log("Loading strategies", this.get('data'));
        this.nodes = [];
        this.edges = [];
        strategies = this.get('model').filterProperty('selected', true);
        self = this;
        return strategies.forEach(function(strategy) {
          return self.buildNode(strategy);
        });
      }
    },
    selectedStrategiesCount: (function() {
      return this.get('model').filterProperty('selected', true).get('length');
    }).property('strategies.@each.strategy'),
    buildNode: function(strategy) {
      var node, self;
      console.log("Building the node for ", strategy.get('id'));
      self = this;
      node = {};
      node['id'] = strategy.get('id');
      node['description'] = strategy.get('description');
      node['selected'] = strategy.get('selected');
      return this.store.find('administration', strategy.get('administration.id')).then(function(administration) {
        node['group'] = administration.get('name');
        node['color'] = administration.get('color');
        node['administration_id'] = administration.get('id');
        return self.store.find('focusarea', strategy.get('focusarea.id')).then(function(focusarea) {
          node['focusarea'] = focusarea.get('definition');
          node['focusarea_id'] = focusarea.get('id');
          self.get('nodes').pushObject(node);
          return console.log("NODE:", self.get('nodes'));
        });
      });
    }
  });

}).call(this);

//# sourceMappingURL=graph.map
