// Generated by CoffeeScript 1.7.1
(function() {
  App.ThemesNewController = Ember.ObjectController.extend({
    actions: {
      submit: function() {
        var self, shouldSave, theme;
        theme = this.get('model');
        shouldSave = true;
        if (Ember.isEmpty(theme.get('definition'))) {
          this.notify.danger("Definition cannot be empty.");
          shouldSave = false;
        }
        if (shouldSave) {
          self = this;
          return theme.save().then(function(savedTheme) {
            App.log('Saving the theme and transitioning to the theme\'s focusareas', 'App.ThemesNewController.submit', savedTheme.get("id"));
            return self.transitionToRoute('/themes/' + theme.get('id') + '/focusareas');
          });
        } else {
          return this.transitionToRoute('/themes/new');
        }
      },
      cancel: function() {
        this.get('model').rollback();
        return this.transitionToRoute('/themes');
      }
    }
  });

}).call(this);

//# sourceMappingURL=themesNew.map
