// Generated by CoffeeScript 1.7.1
(function() {
  App.ThemesEditController = Ember.ObjectController.extend({
    actions: {
      update: function() {
        var self, shouldSave, theme;
        theme = this.get('model');
        shouldSave = true;
        if (Ember.isEmpty(theme.get('definition'))) {
          this.notify.danger("Definition cannot be empty.");
          shouldSave = false;
        }
        if (shouldSave) {
          console.log("Finding the focusareas");
          self = this;
          return this.store.find("focusarea", {
            theme_id: theme.get('id')
          }).then(function(focusareas) {
            console.log("focusarea->", focusareas);
            return theme.get('focusareas').then(function(themeFocusareas) {
              themeFocusareas.clear();
              focusareas.forEach(function(focusarea) {
                return themeFocusareas.pushObject(focusarea);
              });
              return theme.save().then(function() {
                console.log("SAVED FOCUSAREA RESOLVED");
                return self.transitionToRoute('/themes/' + theme.get('id') + '/focusareas');
              });
            });
          });
        } else {
          return this.transitionToRoute('/themes/edit');
        }
      },
      "delete": function() {
        var self, theme;
        theme = this.get('model');
        self = this;
        return theme.get('focusareas').then(function(focusareas) {
          if (focusareas.get('length') === 0) {
            return theme.destroyRecord().then(function() {
              return self.transitionToRoute('/themes');
            });
          } else {
            self.notify.danger("Cannot delete " + theme.get('definition') + ". Please delete all the focus areas related to this theme first.");
            return self.transitionToRoute('/themes/' + theme.get('id') + '/focusareas');
          }
        });
      },
      cancel: function() {
        this.get('model').rollback();
        return this.transitionToRoute('/themes/' + this.get('model').get('id') + '/focusareas');
      }
    }
  });

}).call(this);

//# sourceMappingURL=themesEdit.map
