// Generated by CoffeeScript 1.7.1
(function() {
  App.ThemesEditController = Ember.ObjectController.extend({
    actions: {
      update: function() {
        var shouldSave, theme;
        theme = this.get('model');
        shouldSave = true;
        if (Ember.isEmpty(theme.get('definition'))) {
          this.notify.danger("Definition cannot be empty.");
          shouldSave = false;
        }
        if (shouldSave) {
          theme.save();
          return this.transitionToRoute('/themes/' + theme.get('id') + '/focusareas');
        } else {
          return this.transitionToRoute('/themes/edit');
        }
      },
      "delete": function() {
        var notify, theme;
        theme = this.get('model');
        notify = this.notify;
        if (this.get('focusareasLength') === 0) {
          theme.destroyRecord();
          return this.transitionToRoute('/themes');
        } else {
          notify.danger("Cannot delete " + theme.get('definition') + ". Please delete all the focus areas related to this theme first.");
          return this.transitionToRoute('/themes/' + theme.id + '/focusareas');
        }
      },
      cancel: function() {
        this.get('model').rollback();
        return this.transitionToRoute('/themes/' + this.get('model').get('id') + '/focusareas');
      }
    }
  });

}).call(this);

//# sourceMappingURL=themesEdit.map
