// Generated by CoffeeScript 1.7.1
(function() {
  App.ThemesEditController = Ember.ObjectController.extend({
    actions: {
      update: function() {
        var shouldSave, theme;
        theme = this.get('model');
        shouldSave = true;
        if (Ember.isEmpty(theme.get('definition'))) {
          this.notify.danger("Definition cannot be empty.");
          shouldSave = false;
        }
        if (shouldSave) {
          theme.save();
          return this.transitionToRoute('/themes');
        } else {
          return this.transitionToRoute('/themes/edit');
        }
      },
      "delete": function() {
        var administration;
        administration = this.get('model');
        administration.destroyRecord();
        return this.transitionToRoute('/themes');
      },
      cancel: function() {
        this.get('model').rollback();
        return this.transitionToRoute('/themes');
      }
    }
  });

}).call(this);

//# sourceMappingURL=themesEdit.map
