// Generated by CoffeeScript 1.7.1
(function() {
  App.XGraphSummaryComponent = Ember.Component.extend({
    dataSet: null,
    nodes: [],
    edges: [],
    grouped: {},
    orderedByGroup: null,
    processDataSet: (function() {
      var dataSet, grouped;
      dataSet = this.get('dataSet');
      this.set('nodes', dataSet['nodes']);
      this.set('edges', dataSet['edges']);
      grouped = {};
      dataSet['nodes'].forEach(function(node) {
        if (grouped[node.group] != null) {
          return grouped[node.group].push(node);
        } else {
          return grouped[node.group] = [node];
        }
      });
      this.set('grouped', grouped);
      return this.get('dataSetToHtml');
    }).observes('dataSet').on('didInsertElement'),
    dataSetToHtml: (function() {
      var groupedNodes, html;
      html = "<div>";
      groupedNodes = this.get('grouped');
      Object.keys(groupedNodes).forEach(function(group) {
        var nodes;
        nodes = groupedNodes[group];
        html += "<div class='well well-sm' style='margin-bottom: 0px; background-color:" + nodes[0]['color'] + ";'>" + group + "</div>";
        html += "<div>";
        nodes.forEach(function(value) {
          return html += "<div>" + value['description'] + "</div>";
        });
        return html += "</div><br>";
      });
      html += "</div>";
      console.log(html);
      return $('#ordered_by_group').html(html);
    }).property('grouped.@each')
  });

}).call(this);

//# sourceMappingURL=graphSummary.map
