// Generated by CoffeeScript 1.7.1
(function() {
  App.XGraphSummaryComponent = Ember.Component.extend({
    dataSet: null,
    nodes: [],
    edges: [],
    grouped: {},
    orderedByGroup: null,
    processDataSet: (function() {
      var dataSet, grouped;
      dataSet = this.get('dataSet');
      this.set('nodes', dataSet['nodes']);
      this.set('edges', dataSet['edges']);
      grouped = {};
      dataSet['nodes'].forEach(function(node) {
        if (grouped[node.group] != null) {
          return grouped[node.group].push(node);
        } else {
          return grouped[node.group] = [node];
        }
      });
      return this.set('grouped', grouped);
    }).observes('dataSet').on('didInsertElement'),
    dataSetToHtml: (function() {
      var html, key, values, _i, _len, _ref;
      html = "<div>";
      if (this.grouped != null) {
        console.log("DATA!!!!", this.grouped);
        _ref = this.grouped;
        for (values = _i = 0, _len = _ref.length; _i < _len; values = ++_i) {
          key = _ref[values];
          console.log("!!!!", key);
        }
      }
      html += "</div>";
      return this.set('orderedByGroup', html);
    }).observes('grouped')
  });

}).call(this);

//# sourceMappingURL=graphSummary.map
