// Generated by CoffeeScript 1.7.1
(function() {
  App.XNotifyComponent = Ember.Component.extend({
    classNames: "notify-messages",
    messages: Ember.computed.alias("notify")
  });

  App.XNotifyMessageComponent = Ember.Component.extend({
    classNames: ["x-notify-message-container"],
    classNameBindings: ["insertState"],
    insertState: "pre-insert",
    didInsertElement: function() {
      var self;
      self = this;
      self.$().bind("webkitTransitionEnd", function(event) {
        if (self.get("insertState") === "destroyed") {
          self.notify.removeObject(self.get("message"));
        }
      });
      Ember.run.later((function() {
        self.set("insertState", "inserted");
      }), 250);
      if (self.notify.timeout) {
        Ember.run.later((function() {
          self.set("insertState", "destroyed");
        }), self.notify.timeout);
      }
    },
    willDestroyElement: function() {
      var self;
      self = this;
      self.set("insertState", "destroyed");
    },
    click: function() {
      var self;
      self = this;
      self.set("insertState", "destroyed");
    }
  });

}).call(this);

//# sourceMappingURL=notify.map
