// Generated by CoffeeScript 1.7.1
(function() {
  Ember.Handlebars.helper("capitalize", function(value) {
    if (Ember.I18n.exists('notify.' + value)) {
      return Ember.I18n.t('notify.' + value);
    } else {
      return value.capitalize();
    }
  });

  window.App = Ember.Application.create({
    LOG_TRANSITIONS: true,
    LOG_TRANSITIONS_INTERNAL: true,
    LOG_VIEW_LOOKUPS: true,
    LOG_BINDINGS: true,
    LOG_ACTIVE_GENERATION: true
  });

  App.ApplicationAdapter = DS.LSAdapter.extend({
    namespace: 'sip'
  });

  DS.LSAdapter.create({
    namespace: 'sip'
  });

}).call(this);

//# sourceMappingURL=app.map
