App.Router.map ->
    @resource("administrations")
    @resource("administrations.new", {path:'/administrations/new'})
    @resource("administrations.edit", {path:'/administrations/edit/:id'})
    @resource('themes')
    @resource('themes.new', {path:'/themes/new'})
    @resource('themes.edit', {path:'/themes/edit/:id'})
    @resource('focusareas')
    @resource('focusareas.new', {path:'/focusareas/new'})
    @resource('focusareas.edit', {path:'/focusareas/edit/:id'})
    @resource('about')
    @resource('settings')
