// Generated by CoffeeScript 1.7.1
(function() {
  App.Router.map(function() {
    this.resource("administrations");
    this.resource("administrations.new", {
      path: '/administrations/new'
    });
    this.resource("administrations.edit", {
      path: '/administrations/edit/:id'
    });
    this.resource('themes');
    this.resource('themes.new', {
      path: '/themes/new'
    });
    this.resource('themes.edit', {
      path: '/themes/edit/:id'
    });
    this.resource('focusareas');
    this.resource('focusareas.new', {
      path: '/focusareas/new'
    });
    this.resource('focusareas.edit', {
      path: '/focusareas/edit/:id'
    });
    this.resource('about');
    return this.resource('settings');
  });

}).call(this);

//# sourceMappingURL=routes.map
