// Generated by CoffeeScript 1.7.1
(function() {
  App.Router.map(function() {
    this.resource("administrations", function() {
      return this.route("new");
    });
    this.route('about');
    this.route('themes');
    return this.route('focusareas');
  });

  App.AdministrationsRoute = Ember.Route.extend({
    mode: function() {
      return '';
    }
  });

}).call(this);

//# sourceMappingURL=routes.map
