// Generated by CoffeeScript 1.7.1
(function() {
  App.Router.map(function() {
    this.resource("administrations");
    this.resource("administrations.new", {
      path: '/administrations/new'
    });
    this.route('about');
    this.route('themes');
    return this.route('focusareas');
  });

  App.AdministrationsNewRoute = Ember.Route.extend({
    model: function() {
      return this.store.createRecord('administration');
    },
    actions: {
      submit: function() {
        console.log("Hell Yeah");
        return this.transitionTo('/administrations');
      }
    }
  });

}).call(this);

//# sourceMappingURL=routes.map
