// Generated by CoffeeScript 1.7.1
(function() {
  Ember.I18n.translations = {
    administrations: {
      index: {
        title: "Forvaltning"
      },
      "new": {
        title: "Opret nye forvaltning"
      }
    },
    notify: {
      danger: "Fejl",
      warning: "Bemærk",
      info: "Info",
      success: "Success"
    }
  };

}).call(this);

//# sourceMappingURL=translations.map
