// Generated by CoffeeScript 1.7.1
(function() {
  Ember.I18n.translations = {
    application: {
      title: "Strategiske Indsatsplan",
      navbar: {
        index: "Oversigt",
        edit: "Redigere SIP",
        administrations: "Forvaltninger",
        themes: "Indsatsplaner",
        settings: "Indstillinger",
        about: "Om"
      },
      footer: {
        organization: "Herning Kommune"
      }
    },
    index: {
      heading: "Oversigt",
      description: ""
    },
    administrations: {
      index: {
        add: "Tilføj forvaltning",
        name: "Forvaltning",
        color: "Farve"
      },
      "new": {
        heading: "Opret nye forvaltning",
        name: "Navn",
        color: "Farve",
        create: "Opret"
      },
      edit: {
        heading: "Redigere forvaltningen",
        name: "Navn",
        color: "Farve",
        update: "Opdatere",
        "delete": "Slet",
        cancel: "Annullere",
        modal: {
          info: "Er du sikker at du vil gerne slette {{name}}"
        }
      }
    },
    themes: {
      index: {
        heading: "Temaer",
        add: 'Tilføj tema',
        definition: 'Beskrivelse'
      },
      "new": {
        heading: "Opret nye tema",
        definition: "Beksrivelse",
        create: "Opret"
      },
      edit: {
        heading: "Redigere tema",
        name: "Beskrivelse",
        update: "Opdatere",
        "delete": "Slet",
        cancel: "Annullere",
        modal: {
          info: "Er du sikker at du vil gerne slette {{definition}}"
        }
      }
    },
    focusareas: {
      index: {
        heading: "Fokus områder",
        add: 'Tilføj fokus område',
        definition: 'Beskrivelse',
        theme: 'Tema'
      },
      "new": {
        heading: "Opret nye fokus område",
        definition: "Beksrivelse",
        create: "Opret"
      },
      edit: {
        heading: "Redigere fokus område",
        name: "Beskrivelse",
        update: "Opdatere",
        "delete": "Slet",
        cancel: "Annullere",
        modal: {
          info: "Er du sikker at du vil gerne slette {{definition}}"
        }
      }
    },
    notify: {
      danger: "Fejl",
      warning: "Bemærk",
      info: "Info",
      success: "Success"
    }
  };

}).call(this);

//# sourceMappingURL=translations.map
