// Generated by CoffeeScript 1.7.1
(function() {
  App.AdministrationStrategyView = Ember.View.extend({
    didInsertElement: function() {},
    keyPress: function() {
      return console.log("keypress");
    },
    click: function() {
      return console.log("click");
    }
  });

}).call(this);

//# sourceMappingURL=administrationStrategy.map
