// Generated by CoffeeScript 1.7.1
(function() {
  App.ColorPicker = Em.View.extend({
    didInsertElement: function() {
      return $('#color').colorpicker();
    }
  });

}).call(this);

//# sourceMappingURL=colorPicker.map
