// Generated by CoffeeScript 1.7.1
(function() {
  App.GraphView = Ember.View.extend({
    willInsertElement: function() {
      return this.get("controller").send("loadStrategies");
    }
  });

}).call(this);

//# sourceMappingURL=graph.map
