// Generated by CoffeeScript 1.7.1
(function() {
  App.StrategyTabPaneView = Ember.View.extend({
    tagName: "div",
    classNames: ['strategies-administrations-tab tab-pane fade in'],
    classNameBindings: ['isActive:active'],
    isActive: (function() {
      return this.get('firstObject').get('id') === this.get('administration_id');
    }).property("controller.model")
  });

}).call(this);

//# sourceMappingURL=strategyTabPaneView.map
