// Generated by CoffeeScript 1.7.1
(function() {
  App.StrategyView = Ember.View.extend({
    templateName: 'strategy',
    controllerName: 'App.StrategyController',
    didInsertElement: function() {},
    keyPress: function() {
      return console.log("keypress");
    },
    click: function() {
      return console.log("click");
    }
  });

}).call(this);

//# sourceMappingURL=strategy.map
