// Generated by CoffeeScript 1.7.1
(function() {
  App.Administration = DS.Model.extend({
    name: DS.attr('string'),
    color: DS.attr('string')
  });

}).call(this);

//# sourceMappingURL=administration.map
