// Generated by CoffeeScript 1.7.1
(function() {
  App.FocusareaSerializer = DS.ActiveModelSerializer.extend(DS.EmbeddedRecordsMixin).extend({
    attrs: {
      strategies: {
        serialize: "ids",
        deserialize: "ids"
      }
    }
  });

  App.Focusarea = DS.Model.extend({
    definition: DS.attr('string'),
    theme: DS.belongsTo('theme', {
      embedded: 'always'
    }),
    strategies: DS.hasMany('strategy', {
      async: true
    }),
    hashedID: (function() {
      return "#" + this.get('id');
    }).property("id")
  });

}).call(this);

//# sourceMappingURL=focusarea.map
