// Generated by CoffeeScript 1.7.1
(function() {
  Ember.Notify = Ember.ArrayProxy.extend({
    content: Ember.A(),
    timeout: 5000,
    pushObject: function(object) {
      object.typeClass = "alert-" + object.type;
      this._super(object);
    },
    danger: function(message) {
      console.log("Notify: " + message);
      this.pushObject({
        type: "danger",
        message: message
      });
    },
    warning: function(message) {
      console.log("Notify: " + message);
      this.pushObject({
        type: "warning",
        message: message
      });
    },
    info: function(message) {
      console.log("Notify: " + message);
      this.pushObject({
        type: "info",
        message: message
      });
    },
    success: function(message) {
      console.log("Notify: " + message);
      this.pushObject({
        type: "success",
        message: message
      });
    }
  });

  Ember.Application.initializer({
    name: "registerNotifyMessages",
    initialize: function(container, application) {
      application.register("notify:main", Ember.Notify);
    }
  });

  Ember.Application.initializer({
    name: "injectNotifyMessages",
    initialize: function(container, application) {
      application.inject("controller", "notify", "notify:main");
      application.inject("component", "notify", "notify:main");
      application.inject("route", "notify", "notify:main");
    }
  });

}).call(this);

//# sourceMappingURL=notify.map
