// Generated by CoffeeScript 1.7.1
(function() {
  Ember.Utility = Ember.Object.extend({
    updateOrSave: function(obj, administration) {
      var count, shouldSave;
      shouldSave = true;
      if (Ember.isEmpty(administration.get('name'))) {
        obj.notify.danger("Name cannot be empty.");
        shouldSave = false;
      }
      count = 0;
      obj.store.all('administration').forEach(function(record) {
        if (record.get('name') === administration.get('name')) {
          return count += 1;
        }
      });
      if (count > 1) {
        obj.notify.danger(administration.get('name') + " is already used.");
        shouldSave = false;
      }
      if (Ember.isEmpty(administration.get('color'))) {
        obj.notify.danger("Color cannot be empty.");
        shouldSave = false;
      }
      if (shouldSave) {
        administration.save();
        return obj.transitionToRoute('/administrations');
      } else {
        return obj.transitionToRoute('/administrations/new');
      }
    }
  });

  Ember.Application.initializer({
    name: "registerUtilities",
    initialize: function(container, application) {
      application.register("utility:main", Ember.Utility);
    }
  });

  Ember.Application.initializer({
    name: "injectUtilities",
    initialize: function(container, application) {
      application.inject("controller", "utility", "utility:main");
    }
  });

}).call(this);

//# sourceMappingURL=utility.map
